library(rgdal)
library(sf)
library(tidyverse)
library(openxlsx)
library(rgeos)
library(tiff)
library(raster)
library(exactextractr)

grid = readOGR("C:/Users/Charlotte Liotta/Desktop/cape_town/data_Cape_Town/data_maps/grid_reference_500.shp")
grid <- spTransform(grid, CRS(proj4string(FU_5yr)))

FU_5yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/fluvial_undefended/FU_1in5.tif')
FU_5yr = crop(FU_5yr, grid)
FU_5yr <- reclassify(FU_5yr, cbind(-9999, NA))
FU_5yr <- reclassify(FU_5yr, cbind(999, NA))
cellStats(FU_5yr, 'min')
cellStats(FU_5yr, 'max')
cellStats(FU_5yr, 'mean')
prop_inondable_5yr = FU_5yr
prop_inondable_5yr <- reclassify(prop_inondable_5yr, cbind(NA, 0))
prop_inondable_5yr <- reclassify(prop_inondable_5yr, cbind(0.005, 10, 1))
FU_5yr_grid = extract(FU_5yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
FU_5yr_grid = data.frame(matrix(unlist(FU_5yr_grid))[,1])
prop_inondable_5yr_grid = extract(prop_inondable_5yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_5yr_grid = data.frame(matrix(unlist(prop_inondable_5yr_grid))[,1])
FU_5yr_grid$prop_inondable = prop_inondable_5yr_grid[,1]
colnames(FU_5yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(FU_5yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/FU_5yr.xlsx')

FU_10yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/fluvial_undefended/FU_1in10.tif')
FU_10yr = crop(FU_10yr, grid)
FU_10yr <- reclassify(FU_10yr, cbind(-9999, NA))
FU_10yr <- reclassify(FU_10yr, cbind(999, NA))
cellStats(FU_10yr, 'min')
cellStats(FU_10yr, 'max')
cellStats(FU_10yr, 'mean')
prop_inondable_10yr = FU_10yr
prop_inondable_10yr <- reclassify(prop_inondable_10yr, cbind(NA, 0))
prop_inondable_10yr <- reclassify(prop_inondable_10yr, cbind(0.005, 10, 1))
FU_10yr_grid = extract(FU_10yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
FU_10yr_grid = data.frame(matrix(unlist(FU_10yr_grid))[,1])
prop_inondable_10yr_grid = extract(prop_inondable_10yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_10yr_grid = data.frame(matrix(unlist(prop_inondable_10yr_grid))[,1])
FU_10yr_grid$prop_inondable = prop_inondable_10yr_grid[,1]
colnames(FU_10yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(FU_10yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/FU_10yr.xlsx')


FU_20yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/fluvial_undefended/FU_1in20.tif')
FU_20yr = crop(FU_20yr, grid)
FU_20yr <- reclassify(FU_20yr, cbind(-9999, NA))
FU_20yr <- reclassify(FU_20yr, cbind(999, NA))
cellStats(FU_20yr, 'min')
cellStats(FU_20yr, 'max')
cellStats(FU_20yr, 'mean')
prop_inondable_20yr = FU_20yr
prop_inondable_20yr <- reclassify(prop_inondable_20yr, cbind(NA, 0))
prop_inondable_20yr <- reclassify(prop_inondable_20yr, cbind(0.005, 10, 1))
FU_20yr_grid = extract(FU_20yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
FU_20yr_grid = data.frame(matrix(unlist(FU_20yr_grid))[,1])
prop_inondable_20yr_grid = extract(prop_inondable_20yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_20yr_grid = data.frame(matrix(unlist(prop_inondable_20yr_grid))[,1])
FU_20yr_grid$prop_inondable = prop_inondable_20yr_grid[,1]
colnames(FU_20yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(FU_20yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/FU_20yr.xlsx')

FU_50yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/fluvial_undefended/FU_1in50.tif')
FU_50yr = crop(FU_50yr, grid)
FU_50yr <- reclassify(FU_50yr, cbind(-9999, NA))
FU_50yr <- reclassify(FU_50yr, cbind(999, NA))
cellStats(FU_50yr, 'min')
cellStats(FU_50yr, 'max')
cellStats(FU_50yr, 'mean')
prop_inondable_50yr = FU_50yr
prop_inondable_50yr <- reclassify(prop_inondable_50yr, cbind(NA, 0))
prop_inondable_50yr <- reclassify(prop_inondable_50yr, cbind(0.005, 10, 1))
FU_50yr_grid = extract(FU_50yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
FU_50yr_grid = data.frame(matrix(unlist(FU_50yr_grid))[,1])
prop_inondable_50yr_grid = extract(prop_inondable_50yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_50yr_grid = data.frame(matrix(unlist(prop_inondable_50yr_grid))[,1])
FU_50yr_grid$prop_inondable = prop_inondable_50yr_grid[,1]
colnames(FU_50yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(FU_50yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/FU_50yr.xlsx')

FU_75yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/fluvial_undefended/FU_1in75.tif')
FU_75yr = crop(FU_75yr, grid)
FU_75yr <- reclassify(FU_75yr, cbind(-9999, NA))
FU_75yr <- reclassify(FU_75yr, cbind(999, NA))
cellStats(FU_75yr, 'min')
cellStats(FU_75yr, 'max')
cellStats(FU_75yr, 'mean')
prop_inondable_75yr = FU_75yr
prop_inondable_75yr <- reclassify(prop_inondable_75yr, cbind(NA, 0))
prop_inondable_75yr <- reclassify(prop_inondable_75yr, cbind(0.005, 10, 1))
FU_75yr_grid = extract(FU_75yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
FU_75yr_grid = data.frame(matrix(unlist(FU_75yr_grid))[,1])
prop_inondable_75yr_grid = extract(prop_inondable_75yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_75yr_grid = data.frame(matrix(unlist(prop_inondable_75yr_grid))[,1])
FU_75yr_grid$prop_inondable = prop_inondable_75yr_grid[,1]
colnames(FU_75yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(FU_75yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/FU_75yr.xlsx')

FU_100yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/fluvial_undefended/FU_1in100.tif')
FU_100yr = crop(FU_100yr, grid)
FU_100yr <- reclassify(FU_100yr, cbind(-9999, NA))
FU_100yr <- reclassify(FU_100yr, cbind(999, NA))
cellStats(FU_100yr, 'min')
cellStats(FU_100yr, 'max')
cellStats(FU_100yr, 'mean')
prop_inondable_100yr = FU_100yr
prop_inondable_100yr <- reclassify(prop_inondable_100yr, cbind(NA, 0))
prop_inondable_100yr <- reclassify(prop_inondable_100yr, cbind(0.005, 10, 1))
FU_100yr_grid = extract(FU_100yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
FU_100yr_grid = data.frame(matrix(unlist(FU_100yr_grid))[,1])
prop_inondable_100yr_grid = extract(prop_inondable_100yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_100yr_grid = data.frame(matrix(unlist(prop_inondable_100yr_grid))[,1])
FU_100yr_grid$prop_inondable = prop_inondable_100yr_grid[,1]
colnames(FU_100yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(FU_100yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/FU_100yr.xlsx')


FU_200yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/fluvial_undefended/FU_1in200.tif')
FU_200yr = crop(FU_200yr, grid)
FU_200yr <- reclassify(FU_200yr, cbind(-9999, NA))
FU_200yr <- reclassify(FU_200yr, cbind(999, NA))
cellStats(FU_200yr, 'min')
cellStats(FU_200yr, 'max')
cellStats(FU_200yr, 'mean')
prop_inondable_200yr = FU_200yr
prop_inondable_200yr <- reclassify(prop_inondable_200yr, cbind(NA, 0))
prop_inondable_200yr <- reclassify(prop_inondable_200yr, cbind(0.005, 10, 1))
FU_200yr_grid = extract(FU_200yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
FU_200yr_grid = data.frame(matrix(unlist(FU_200yr_grid))[,1])
prop_inondable_200yr_grid = extract(prop_inondable_200yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_200yr_grid = data.frame(matrix(unlist(prop_inondable_200yr_grid))[,1])
FU_200yr_grid$prop_inondable = prop_inondable_200yr_grid[,1]
colnames(FU_200yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(FU_200yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/FU_200yr.xlsx')


FU_250yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/fluvial_undefended/FU_1in250.tif')
FU_250yr = crop(FU_250yr, grid)
FU_250yr <- reclassify(FU_250yr, cbind(-9999, NA))
FU_250yr <- reclassify(FU_250yr, cbind(999, NA))
cellStats(FU_250yr, 'min')
cellStats(FU_250yr, 'max')
cellStats(FU_250yr, 'mean')
prop_inondable_250yr = FU_250yr
prop_inondable_250yr <- reclassify(prop_inondable_250yr, cbind(NA, 0))
prop_inondable_250yr <- reclassify(prop_inondable_250yr, cbind(0.005, 10, 1))
FU_250yr_grid = extract(FU_250yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
FU_250yr_grid = data.frame(matrix(unlist(FU_250yr_grid))[,1])
prop_inondable_250yr_grid = extract(prop_inondable_250yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_250yr_grid = data.frame(matrix(unlist(prop_inondable_250yr_grid))[,1])
FU_250yr_grid$prop_inondable = prop_inondable_250yr_grid[,1]
colnames(FU_250yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(FU_250yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/FU_250yr.xlsx')


FU_500yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/fluvial_undefended/FU_1in500.tif')
FU_500yr = crop(FU_500yr, grid)
FU_500yr <- reclassify(FU_500yr, cbind(-9999, NA))
FU_500yr <- reclassify(FU_500yr, cbind(999, NA))
cellStats(FU_500yr, 'min')
cellStats(FU_500yr, 'max')
cellStats(FU_500yr, 'mean')
prop_inondable_500yr = FU_500yr
prop_inondable_500yr <- reclassify(prop_inondable_500yr, cbind(NA, 0))
prop_inondable_500yr <- reclassify(prop_inondable_500yr, cbind(0.005, 10, 1))
FU_500yr_grid = extract(FU_500yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
FU_500yr_grid = data.frame(matrix(unlist(FU_500yr_grid))[,1])
prop_inondable_500yr_grid = extract(prop_inondable_500yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_500yr_grid = data.frame(matrix(unlist(prop_inondable_500yr_grid))[,1])
FU_500yr_grid$prop_inondable = prop_inondable_500yr_grid[,1]
colnames(FU_500yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(FU_500yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/FU_500yr.xlsx')


FU_1000yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/fluvial_undefended/FU_1in1000.tif')
FU_1000yr = crop(FU_1000yr, grid)
FU_1000yr <- reclassify(FU_1000yr, cbind(-9999, NA))
FU_1000yr <- reclassify(FU_1000yr, cbind(999, NA))
cellStats(FU_1000yr, 'min')
cellStats(FU_1000yr, 'max')
cellStats(FU_1000yr, 'mean')
prop_inondable_1000yr = FU_1000yr
prop_inondable_1000yr <- reclassify(prop_inondable_1000yr, cbind(NA, 0))
prop_inondable_1000yr <- reclassify(prop_inondable_1000yr, cbind(0.005, 10, 1))
FU_1000yr_grid = extract(FU_1000yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
FU_1000yr_grid = data.frame(matrix(unlist(FU_1000yr_grid))[,1])
prop_inondable_1000yr_grid = extract(prop_inondable_1000yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_1000yr_grid = data.frame(matrix(unlist(prop_inondable_1000yr_grid))[,1])
FU_1000yr_grid$prop_inondable = prop_inondable_1000yr_grid[,1]
colnames(FU_1000yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(FU_1000yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/FU_1000yr.xlsx')

P_5yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/pluvial/P_1in5.tif')
P_5yr = crop(P_5yr, grid)
P_5yr <- reclassify(P_5yr, cbind(-9999, NA))
P_5yr <- reclassify(P_5yr, cbind(999, NA))
cellStats(P_5yr, 'min')
cellStats(P_5yr, 'max')
cellStats(P_5yr, 'mean')
prop_inondable_5yr = P_5yr
prop_inondable_5yr <- reclassify(prop_inondable_5yr, cbind(NA, 0))
prop_inondable_5yr <- reclassify(prop_inondable_5yr, cbind(0.005, 10, 1))
P_5yr_grid = extract(P_5yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
P_5yr_grid = data.frame(matrix(unlist(P_5yr_grid))[,1])
prop_inondable_5yr_grid = extract(prop_inondable_5yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_5yr_grid = data.frame(matrix(unlist(prop_inondable_5yr_grid))[,1])
P_5yr_grid$prop_inondable = prop_inondable_5yr_grid[,1]
colnames(P_5yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(P_5yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/P_5yr.xlsx')

P_10yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/pluvial/P_1in10.tif')
P_10yr = crop(P_10yr, grid)
P_10yr <- reclassify(P_10yr, cbind(-9999, NA))
P_10yr <- reclassify(P_10yr, cbind(999, NA))
cellStats(P_10yr, 'min')
cellStats(P_10yr, 'max')
cellStats(P_10yr, 'mean')
prop_inondable_10yr = P_10yr
prop_inondable_10yr <- reclassify(prop_inondable_10yr, cbind(NA, 0))
prop_inondable_10yr <- reclassify(prop_inondable_10yr, cbind(0.005, 10, 1))
P_10yr_grid = extract(P_10yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
P_10yr_grid = data.frame(matrix(unlist(P_10yr_grid))[,1])
prop_inondable_10yr_grid = extract(prop_inondable_10yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_10yr_grid = data.frame(matrix(unlist(prop_inondable_10yr_grid))[,1])
P_10yr_grid$prop_inondable = prop_inondable_10yr_grid[,1]
colnames(P_10yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(P_10yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/P_10yr.xlsx')

P_20yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/pluvial/P_1in20.tif')
P_20yr = crop(P_20yr, grid)
P_20yr <- reclassify(P_20yr, cbind(-9999, NA))
P_20yr <- reclassify(P_20yr, cbind(999, NA))
cellStats(P_20yr, 'min')
cellStats(P_20yr, 'max')
cellStats(P_20yr, 'mean')
prop_inondable_20yr = P_20yr
prop_inondable_20yr <- reclassify(prop_inondable_20yr, cbind(NA, 0))
prop_inondable_20yr <- reclassify(prop_inondable_20yr, cbind(0.005, 10, 1))
P_20yr_grid = extract(P_20yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
P_20yr_grid = data.frame(matrix(unlist(P_20yr_grid))[,1])
prop_inondable_20yr_grid = extract(prop_inondable_20yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_20yr_grid = data.frame(matrix(unlist(prop_inondable_20yr_grid))[,1])
P_20yr_grid$prop_inondable = prop_inondable_20yr_grid[,1]
colnames(P_20yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(P_20yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/P_20yr.xlsx')

P_50yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/pluvial/P_1in50.tif')
P_50yr = crop(P_50yr, grid)
P_50yr <- reclassify(P_50yr, cbind(-9999, NA))
P_50yr <- reclassify(P_50yr, cbind(999, NA))
cellStats(P_50yr, 'min')
cellStats(P_50yr, 'max')
cellStats(P_50yr, 'mean')
prop_inondable_50yr = P_50yr
prop_inondable_50yr <- reclassify(prop_inondable_50yr, cbind(NA, 0))
prop_inondable_50yr <- reclassify(prop_inondable_50yr, cbind(0.005, 10, 1))
P_50yr_grid = extract(P_50yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
P_50yr_grid = data.frame(matrix(unlist(P_50yr_grid))[,1])
prop_inondable_50yr_grid = extract(prop_inondable_50yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_50yr_grid = data.frame(matrix(unlist(prop_inondable_50yr_grid))[,1])
P_50yr_grid$prop_inondable = prop_inondable_50yr_grid[,1]
colnames(P_50yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(P_50yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/P_50yr.xlsx')

P_75yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/pluvial/P_1in75.tif')
P_75yr = crop(P_75yr, grid)
P_75yr <- reclassify(P_75yr, cbind(-9999, NA))
P_75yr <- reclassify(P_75yr, cbind(999, NA))
cellStats(P_75yr, 'min')
cellStats(P_75yr, 'max')
cellStats(P_75yr, 'mean')
prop_inondable_75yr = P_75yr
prop_inondable_75yr <- reclassify(prop_inondable_75yr, cbind(NA, 0))
prop_inondable_75yr <- reclassify(prop_inondable_75yr, cbind(0.005, 10, 1))
P_75yr_grid = extract(P_75yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
P_75yr_grid = data.frame(matrix(unlist(P_75yr_grid))[,1])
prop_inondable_75yr_grid = extract(prop_inondable_75yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_75yr_grid = data.frame(matrix(unlist(prop_inondable_75yr_grid))[,1])
P_75yr_grid$prop_inondable = prop_inondable_100yr_grid[,1]
colnames(P_75yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(P_75yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/P_75yr.xlsx')

P_100yr = raster('C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/South Africa/pluvial/P_1in100.tif')
P_100yr = crop(P_100yr, grid)
P_100yr <- reclassify(P_100yr, cbind(-9999, NA))
P_100yr <- reclassify(P_100yr, cbind(999, NA))
cellStats(P_100yr, 'min')
cellStats(P_100yr, 'max')
cellStats(P_100yr, 'mean')
prop_inondable_100yr = P_100yr
prop_inondable_100yr <- reclassify(prop_inondable_100yr, cbind(NA, 0))
prop_inondable_100yr <- reclassify(prop_inondable_100yr, cbind(0.005, 10, 1))
P_100yr_grid = extract(P_100yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
P_100yr_grid = data.frame(matrix(unlist(P_100yr_grid))[,1])
prop_inondable_100yr_grid = extract(prop_inondable_100yr, grid, fun=mean, weights = TRUE, na.rm=TRUE)
prop_inondable_100yr_grid = data.frame(matrix(unlist(prop_inondable_100yr_grid))[,1])
P_100yr_grid$prop_inondable = prop_inondable_100yr_grid[,1]
colnames(P_100yr_grid) = c("flood_depth", "prop_flood_prone")
write.xlsx(P_100yr_grid, 'C:/Users/Charlotte Liotta/Desktop/cape_town/2. Data/FATHOM/P_100yr.xlsx')
